In [1]:
#Import Library

import numpy as np
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

## Numpy Array Creation

In [3]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [4]:
#Display the type of an object
type(list1)

list

In [5]:
#convert list into Numpy array
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [6]:
#memory address of an object
arr1.data

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.dtype

dtype('int32')

In [9]:
#Convert Integer array to float
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
#Generate evenly spaced numbers (space=1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Generate numbers between 0 to 100 with a space  of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
#Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [13]:
#shape of array
arr2 = np.arange(1, 10)
arr2.shape

(9,)

In [17]:
#Size of array
arr2.size

9

In [18]:
#Dimension
arr2.ndim

1

In [19]:
#Datatype of an object
arr2.dtype

dtype('int32')

In [20]:
#Bytes consumed by one element of an array object
arr2.itemsize

4

In [21]:
#Bytes consumed by an array object
arr2.nbytes

36

In [22]:
#Length of an array
len(arr2)

9

In [23]:
#Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
#Generate an array of ones with given shape 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
#Repeat 10 five times in an array
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [26]:
#Repeat each element in array 'a' thrice
a=np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [27]:
#Array of 10's
np.full(5,10)

array([10, 10, 10, 10, 10])

In [28]:
#Generate array of Odd numbers
ar3 = np.arange(1,20)
ar3[ar3%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
#Generate evnly spaced 4 numbers between 10 20
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [30]:
#Create an array of random values
np.random.random(4)

array([0.03571585, 0.66190557, 0.78052975, 0.23726613])

In [31]:
#Generate an array of Random Integer numbers
np.random.randint(0, 500, 5)

array([301, 472,  28, 476,  31])

In [32]:
#Generate an array of Random Integer numberss
np.random.randint(0, 500, 10)

array([142, 328, 469,  71, 388, 114, 476,  71, 448, 319])