In [1]:
#Import Library

import numpy as np
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

## Numpy Array Creation

In [13]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [14]:
#Display the type of an object
type(list1)

list

In [15]:
#convert list into Numpy array
arr1 = np.array(list1)
arr1

<IPython.core.display.Javascript object>

array([10, 20, 30, 40, 50, 60])

In [6]:
#memory address of an object
arr1.data

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.dtype

dtype('int32')

In [9]:
#Convert Integer array to float
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [10]:
#Generate evenly spaced numbers (space=1) between 0 to 10
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Generate numbers between 0 to 100 with a space  of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
#Generate numbers between 10 to 100 with a space of 10 in descending order
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [13]:
#shape of array
arr2 = np.arange(1, 10)
arr2.shape

(9,)

In [17]:
#Size of array
arr2.size

9

In [18]:
#Dimension
arr2.ndim

1

In [19]:
#Datatype of an object
arr2.dtype

dtype('int32')

In [20]:
#Bytes consumed by one element of an array object
arr2.itemsize

4

In [21]:
#Bytes consumed by an array object
arr2.nbytes

36

In [22]:
#Length of an array
len(arr2)

9

In [23]:
#Generate an array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
#Generate an array of ones with given shape 
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
#Repeat 10 five times in an array
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [26]:
#Repeat each element in array 'a' thrice
a=np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [27]:
#Array of 10's
np.full(5,10)

array([10, 10, 10, 10, 10])

In [28]:
#Generate array of Odd numbers
ar3 = np.arange(1,20)
ar3[ar3%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
#Generate evnly spaced 4 numbers between 10 20
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [30]:
#Create an array of random values
np.random.random(4)

array([0.03571585, 0.66190557, 0.78052975, 0.23726613])

In [31]:
#Generate an array of Random Integer numbers
np.random.randint(0, 500, 5)

array([301, 472,  28, 476,  31])

In [32]:
#Generate an array of Random Integer numberss
np.random.randint(0, 500, 10)

array([142, 328, 469,  71, 388, 114, 476,  71, 448, 319])

In [5]:
# Using random.seed we can generate same number of random numbers
np.random.seed(123)
np.random.randint(0,100,10)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [7]:
#Generate array of Random float numbers
f1=np.random.uniform(4,10, size=(10))
f1

<IPython.core.display.Javascript object>

array([7.19096552, 7.80640575, 9.09659076, 8.34673195, 7.66614106,
       8.3346603 , 5.93775348, 6.17073193, 5.36957939, 5.76228428])

In [8]:
#Extract integer part
np.floor(f1)

<IPython.core.display.Javascript object>

array([7., 7., 9., 8., 7., 8., 5., 6., 5., 5.])

In [9]:
#Truncate decimal part
np.trunc(f1)

<IPython.core.display.Javascript object>

array([7., 7., 9., 8., 7., 8., 5., 6., 5., 5.])

In [10]:
#Convert float array to integer array
f1.astype(int)

array([7, 7, 9, 8, 7, 8, 5, 6, 5, 5])

In [11]:
#Normal distribution (mean = 0, variance = 1)
b2=np.random.randn(10)
b2

<IPython.core.display.Javascript object>

array([-0.74856868,  0.24036728, -1.85563747, -1.7794548 , -2.75022426,
       -0.23415755, -0.69598118, -1.77413406,  2.36160126,  0.03499308])

In [16]:
arr1

array([10, 20, 30, 40, 50, 60])

In [19]:
# Enumerate for Numpy Arrays
for index, value in np.ndenumerate(arr1):
    print(index, value)

<IPython.core.display.Javascript object>

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


### Operations on an Array

In [21]:
arr2 = np.arange(1, 20)
arr2

<IPython.core.display.Javascript object>

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [22]:
# Sum of all elements in an array
arr2.sum()

190

In [23]:
# Cumulative Sum
np.cumsum(arr2)

<IPython.core.display.Javascript object>

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [24]:
# Find min number in an array
arr2.min()

1

In [26]:
# find max number
arr2.max()

19

### Replace elements in array

In [28]:
ar = np.arange(1, 20)
ar

<IPython.core.display.Javascript object>

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
# Replace EVEN numbers with zero
rep1 = np.where(ar%2==0, 0, ar)
print(rep1)

<IPython.core.display.Javascript object>

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [30]:
ar2 = np.array([10,20, 30, 10, 10, 20, 20])
ar2

<IPython.core.display.Javascript object>

array([10, 20, 30, 10, 10, 20, 20])

In [31]:
# Replace 10 with value 99
rep2= np.where(ar2 == 10, 99, ar2)
print(rep2)

<IPython.core.display.Javascript object>

[99 20 30 99 99 20 20]


In [32]:
p2=np.arange(0, 100, 10)
p2

<IPython.core.display.Javascript object>

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Replace values at INDEX loc 0,3,5 with 33, 55, 99
np.put(p2, [])